### PR TITLE
Upgrade Ruby and Gems

### PR DESCRIPTION
**Pull request by danielmorrison**

### CODE REVIEW

**Comment by laserlemon** [comment]
There are some major gem upgrades here. Does Honeybadger need to be configured differently? Tilt and Twilio gems are also major upgrades? Do we Do It Live™ and test out the system?

**Comment by albus522** [comment]
Tilt is just a sinatra dependency. Twilio does look like it has a configuration change but it may not be required. Honeybadger looks like it should just work, but it has one of the worst change logs I have seen

**Comment by laserlemon** [comment]
I think Honeybadger now looks for `HONEYBADGER_API_KEY` in `ENV` automatically, without the need to configure in code.

**Comment by danielmorrison** [comment]
Feel free to mark as WIP, I'm on a plane for a while.

**Comment by laserlemon** [comment]
I think Honeybadger should work. Not sure about Twilio.

**Comment by albus522** [comment]
Aren't you supposed to be complaining about not having adequate internet connectivity from your chair in the sky?

**Comment by danielmorrison** [comment]
I thought Honeybadger would Just Work™ since we use the correct ENV var, but I did have to rejigger the config block.

Twilio _shouldn't_ change anything we use.

**Comment by danielmorrison** [comment]
Tested manually on heroku. Works. Love the new squirrel graphic above!

**Pull request merged**
